x-base-config: &base-config
  image: mi-chatwoot:4.7
  volumes:
    - chatwoot-storage:/app/storage
  environment:
    - FRONTEND_URL=${FRONTEND_URL}
    - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    - RAILS_ENV=${RAILS_ENV}
    - NODE_ENV=${NODE_ENV}
    - INSTALLATION_ENV=${INSTALLATION_ENV}
    - RAILS_LOG_TO_STDOUT=${RAILS_LOG_TO_STDOUT}
    - LOG_LEVEL=${LOG_LEVEL}
    - DEFAULT_LOCALE=${DEFAULT_LOCALE}
    - POSTGRES_HOST=${POSTGRES_HOST}
    - POSTGRES_PORT=${POSTGRES_PORT}
    - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    - POSTGRES_USERNAME=${POSTGRES_USERNAME}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - REDIS_URL=${REDIS_URL}
    - ENABLE_ACCOUNT_SIGNUP=${ENABLE_ACCOUNT_SIGNUP}
    - ACTIVE_STORAGE_SERVICE=${ACTIVE_STORAGE_SERVICE}
    - STORAGE_BUCKET_NAME=${STORAGE_BUCKET_NAME}
    - STORAGE_ACCESS_KEY_ID=${STORAGE_ACCESS_KEY_ID}
    - STORAGE_SECRET_ACCESS_KEY=${STORAGE_SECRET_ACCESS_KEY}
    - STORAGE_REGION=${STORAGE_REGION}
    - STORAGE_FORCE_PATH_STYLE=${STORAGE_FORCE_PATH_STYLE}
    - STORAGE_ENDPOINT=${STORAGE_ENDPOINT}
    - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
    - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
    - GOOGLE_OAUTH_CALLBACK_URL=${GOOGLE_OAUTH_CALLBACK_URL}
    - SMTP_ADDRESS=${SMTP_ADDRESS}
    - SMTP_PORT=${SMTP_PORT}
    - SMTP_USERNAME=${SMTP_USERNAME}
    - SMTP_PASSWORD=${SMTP_PASSWORD}
    - SMTP_DOMAIN=${SMTP_DOMAIN}
    - SMTP_AUTHENTICATION=${SMTP_AUTHENTICATION}
    - SMTP_ENABLE_STARTTLS_AUTO=${SMTP_ENABLE_STARTTLS_AUTO}
    - MAILER_SENDER_EMAIL=${MAILER_SENDER_EMAIL}
    - MAILER_SENDER_NAME=${MAILER_SENDER_NAME}
    #- AWS_CHECKSUM_CALCULATION=when_required
    - AWS_SDK_CONFIG_OPT_OUT=1
    - AWS_CHECKSUM_CALCULATION=when_supported

services:
  chatwoot-rails:
    <<: *base-config
    depends_on:
      chatwoot-postgres:
        condition: service_healthy
      chatwoot-redis:
        condition: service_started
    entrypoint: /app/docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'sh', '-c', 'rails db:chatwoot_prepare && rails s -p 3000 -b 0.0.0.0']
    restart: always
    ports:
     - "3000:3000"

  chatwoot-sidekiq:
    <<: *base-config
    depends_on:
      chatwoot-postgres:
        condition: service_healthy
      chatwoot-redis:
        condition: service_started
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always

  chatwoot-postgres:
    image: pgvector/pgvector:pg16
    restart: always
    volumes:
      - chatwoot-postgres-data:/var/lib/postgresql/data
      - ./init-vector.sql:/docker-entrypoint-initdb.d/init-vector.sql
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: >
      postgres
        -c max_connections=200
        -c shared_buffers=4GB
        -c effective_cache_size=12GB
        -c work_mem=64MB
        -c maintenance_work_mem=1GB
        -c checkpoint_completion_target=0.9
        -c wal_buffers=64MB
        -c default_statistics_target=200
        -c random_page_cost=1.1
        -c effective_io_concurrency=200
        -c min_wal_size=1GB
        -c max_wal_size=4GB
        -c max_worker_processes=4
        -c max_parallel_workers_per_gather=2
        -c max_parallel_workers=4
        -c max_parallel_maintenance_workers=2
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DATABASE}']
      interval: 10s
      timeout: 5s
      retries: 5

  chatwoot-redis:
    image: redis:alpine
    restart: always
    command: ['sh', '-c', 'redis-server --requirepass "$REDIS_PASSWORD"']
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - chatwoot-redis-data:/data

volumes:
  chatwoot-storage:
  chatwoot-postgres-data:
  chatwoot-redis-data: